### ISSUE TITLE
请问支持ListView、RecyclerView等滑动的列表控件中的某个Item在滑动出现后自动弹出么?

### ISSUE THREAD

**Issue by KaelInvoker** [samlss/Lighter#2]
看Demo都是点击item后出现，但实际应用中应该都是某个item滑动出来的时候，判断如果是第一次看到就自动弹出引导图。请问这种效果支持么？

**Comment by samlss** [comment]
你自己监听滑动结束，再传view显示

**Comment by samlss** [comment]
> 看Demo都是点击item后出现，但实际应用中应该都是某个item滑动出来的时候，判断如果是第一次看到就自动弹出引导图。请问这种效果支持么？

你自己监听滑动结束，再传view显示

**Comment by KaelInvoker** [comment]
您好，Demo中能加个这样的例子么？

**Comment by samlss** [comment]
> 您好，Demo中能加个这样的例子么？

加我QQ729717222，我晚点给你写个示例
