### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by TopTime1** [samlss/Lighter#6]
为什么有的会偏移？求指教
![image](https://user-images.githubusercontent.com/7701170/54816506-5afd4600-4ccf-11e9-8606-d5fd0a7e83d0.png)
 Lighter.with(this)
                .setBackgroundColor(0xB3000000)
                .setOnLighterListener(new OnLighterListener() {
                    @Override
                    public void onShow(int index) {
                        Toast.makeText(getApplicationContext(), "正在显示第" + (index + 1) + "高亮", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void onDismiss() {
                        Toast.makeText(getApplicationContext(), "高亮已全部显示完毕", Toast.LENGTH_SHORT).show();
                    }
                })
                .addHighlight(new LighterParameter.Builder()
                        .setHighlightedViewId(R.id.pb_left_head_layout)
                        .setTipView(view)
                        .setLighterShape(new RectShape(5, 5, 30))
                        .setTipViewRelativeDirection(Direction.BOTTOM)
                        .setTipViewRelativeOffset(new MarginOffset(0, 0, 5, 0))
                        .build())
                .addHighlight(new LighterParameter.Builder()
                        .setHighlightedViewId(R.id.pb_right_head_layout)
                        .setTipView(view)
                        .setLighterShape(new RectShape(5, 5, 30))
                        .setTipViewRelativeDirection(Direction.BOTTOM)
                        .setTipViewRelativeOffset(new MarginOffset(0, 0, 5, 0))
                        .build())
                .addHighlight(new LighterParameter.Builder()
                        .setHighlightedViewId(R.id.pb_current_question_tv)
                        .setTipView(view)
                        .setLighterShape(new RectShape(5, 5, 30))
                        .setTipViewRelativeDirection(Direction.BOTTOM)
//                        .setTipViewRelativeOffset(new MarginOffset(0, 0, 5, 0))
                        .build())
                .show();

**Comment by TopTime1** [comment]
.setTipLayoutId(R.layout.guide_layout),就没这个问题

**Comment by samlss** [comment]
Solved， thanks for your commention。
