### ISSUE TITLE
setTipLayoutId调用布局的问题

### ISSUE THREAD

**Issue by gkblack** [samlss/Lighter#7]
setTipLayoutId调用的布局如果宽高都是match_parent的就无法完全显示

**Comment by samlss** [comment]
> setTipLayoutId调用的布局如果宽高都是match_parent的就无法完全显示

因为tip layout使用match_parent的话，tip view就是适应屏幕全屏的。例如Lighter.with(‘acivity’)的话，tip view就会铺满整个屏幕，但是tip view的位置又是相对于highlighted view，如果这时tip view在highlighted view下面的话，整个tip view就会向下移动，就有可能造成tip view无法完全显示。

**Comment by gkblack** [comment]
好的
